// Every user-facing string, in one place.

export const copy = {
  meta: {
    title: "TMail — Access your inbox",
    inboxTitle: "Inbox · TMail",
  },
  header: {
    home: "TMail home",
  },
  landing: {
    eyebrow: "Secure inbox access",
    title: "Access your email inbox",
    subtitle: "Enter your email address to access incoming messages.",
    label: "Email address",
    placeholder: "Enter your email address",
    hint: "Use the email address provided with your account.",
    submit: "Access Inbox",
    submitting: "Accessing your inbox…",
    clear: "Clear email address",
    continueWith: "Continue with {email}",
    errors: {
      empty: "Enter your email address.",
      invalid: "Please enter a valid email address.",
      unsupported: "This email address isn't supported. Use the email provided with your account.",
    },
    servicesTitle: "Supported services",
    servicesCaption: "Sign-in and verification emails from these services arrive here.",
  },
  inbox: {
    title: "Inbox",
    copyEmail: "Copy email",
    emailCopied: "Email copied",
    changeEmail: "Change email",
    unread: "{n} unread",
    messages: "Messages",
    refresh: "Refresh",
    refreshAria: "Check for new messages",
    autoRefresh: "Auto-refresh enabled",
    lastChecked: "Last checked {time}",
    status: {
      live: "Connected",
      checking: "Checking for new messages…",
      offline: "Offline",
      reconnecting: "Reconnecting…",
    },
    loading: "Checking for new messages…",
    waitingTitle: "Waiting for incoming email…",
    waitingBody: "Your inbox is empty. New messages from supported services will appear here automatically.",
    errorTitle: "Unable to load your inbox",
    unavailableTitle: "This inbox is currently unavailable.",
    unavailableBody: "Check the email address and try again.",
    retry: "Retry",
    offlineTitle: "You're offline",
    offlineBody: "We'll check for new messages as soon as you're back online.",
    noSubject: "(no subject)",
    noPreview: "No preview available",
    unknownSender: "Unknown sender",
    unreadLabel: "Unread",
    hasAttachments: "Has attachments",
    codeLabel: "Code",
    listLabel: "Messages",
    newEmail: "New email received",
    newEmails: "{n} new emails received",
    newCode: "New verification code",
  },
  code: {
    title: "Verification code",
    copy: "Copy code",
    copyShort: "Copy",
    copied: "Copied",
    copiedToast: "Verification code copied",
    copyAria: "Copy verification code {code}",
    expiryHint: "Use it soon — codes usually expire within minutes.",
  },
  reader: {
    back: "Back to inbox",
    close: "Close email",
    delete: "Delete",
    to: "To",
    received: "Received {time}",
    attachments: "Attachments ({n})",
    download: "Download {name}",
    emptyTitle: "Select an email to read",
    emptyBody: "Choose a message from your inbox to view it here.",
    goneTitle: "This email is no longer available",
    goneBody: "It may have been deleted.",
    contentTitle: "Email content",
    noContent: "(This email has no content)",
  },
  dialog: {
    deleteTitle: "Delete this email?",
    deleteBody: "“{subject}” will be permanently deleted. This can't be undone.",
    deleteConfirm: "Delete email",
    cancel: "Cancel",
    deleting: "Deleting…",
  },
  toast: {
    deleted: "Email deleted",
    deleteFailed: "Couldn't delete this email. It may already be gone.",
    copyFailed: "Couldn't copy. Select the text and copy it manually.",
    dismiss: "Dismiss notification",
  },
  errors: {
    INVALID_INPUT: "Please enter a valid email address.",
    NOT_FOUND: "This inbox is currently unavailable.",
    RATE_LIMITED: "Too many requests. Please wait a moment and try again.",
    TIMEOUT: "The mail server is taking too long. Please try again.",
    NETWORK: "Can't reach the mail server right now.",
    UPSTREAM: "The mail server is having trouble. Please try again.",
    INVALID_RESPONSE: "The mail server is having trouble. Please try again.",
    OFFLINE: "You're offline. Check your connection and try again.",
    generic: "Something went wrong. Please try again.",
  },
  footer: {
    note: "Keep your email address private — anyone who has it can view this inbox.",
    rights: "© TMail",
  },
  time: {
    justNow: "just now",
  },
};

export type Copy = typeof copy;

/** "Hello {name}" + { name: "x" } → "Hello x" */
export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(vars[key] ?? `{${key}}`));
}
